steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/renukeswarchintagcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/renukeswarchinta/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/meta-origin-236703/gcp-cd-codelab:$REVISION_ID",
        "-f",
        "Dockerfile",
        ".",
      ]
images:
  - "gcr.io/meta-origin-236703/gcp-cd-codelab:$REVISION_ID"
